### ISSUE TITLE
菜单栏鼠标悬浮时看不清文字

### ISSUE THREAD

**Issue by zhiyiYo** [hliu202/typora-purple-theme#17]
如下图所示，当鼠标悬浮到菜单项上面时，背景色和文字颜色都很亮，导致看不清字
![屏幕截图 2021-04-22 135314](https://user-images.githubusercontent.com/65096819/115663329-ecd65200-a372-11eb-8f90-415e1ac2e702.png)

**Comment by voidswordQQJ** [comment]
建议先重装一下 Typora 或者最新版的主题，如果不行可以把运行环境发一下（Typora 版本，主题版本，操作系统这些）方便之后判断

**Comment by zhiyiYo** [comment]
**操作系统**：Win10 21H1
**Typora** ：version 0.9.98(beta)
**主题版本**：直接下载的仓库源代码，不是在release里面下的

**Comment by voidswordQQJ** [comment]
刚刚测试了一下，使用记事本打开你目前使用的主题css文件，在最后面添加这一段：

```css
.megamenu-menu-list:not(.saved) li a:hover,
.megamenu-menu-list li a.active {
    background-color: #202B33;
    color: white;
}
```

background-color 是鼠标靠近后背景的颜色
color 则是字体颜色

![image](https://user-images.githubusercontent.com/53446819/115674240-119add00-a313-11eb-992d-4cdac9ddf2d5.png)
