### ISSUE TITLE
求出一个粉色主题

### ISSUE THREAD

**Issue by Riku-tei** [hliu202/typora-purple-theme#19]
一直在用紫色主题那个,想要一个粉色主题的qaq

**Comment by voidswordQQJ** [comment]
@Riku-tei  谢邀，凌晨3点正在睡觉，突然听到手机收到邮件我立马就从床上起来了，很快啊（笑）

其实要自定义的话可以参考 README 文件最下面的说明：

> ## 关于自定义
> 
> 可以很容易自定义喜欢的色调，只需要 copy 任一 `purpe-xxx.css`，在其中修改或添加配置即可

这里给出一个粉色主题的例子（在主题目录下新创建一个 purple-pink.css 文件复制进去）：

```css
@import "./purple.css";

:root {
  --title-color: var(--text-color);
  --link-color: #F48FB1;
  --code-color: #F06292;
}

blockquote {
  border-left: 0.3rem solid var(--border);
}

h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: bold;
}
```

随手写的，基本上就是对希望修改的部分添加 css 代码覆盖原先的部分代码，这个可以直接看 `purple.css` 文件
