### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by PearlLiu-Dev** [hliu202/typora-purple-theme#38]
请问你模板里面的妹子怎么弄呀

**Comment by Ecss11** [comment]
那个是图片，不包含在主题里的

**Comment by narutohyc** [comment]
我也想知道那个图片排版的代码是什么样子的呀

**Comment by Ecss11** [comment]
@narutohyc 可以通过修改图片的 `align` 属性实现排版，参考这个` Issue： #6

**Comment by lyidle** [comment]
就是为了图片来的，结果莫得~

**Comment by hiderua** [comment]
<img width="752" alt="截屏2024-07-22 01 01 10" src="https://github.com/user-attachments/assets/47b27aee-cff4-4277-8830-da59ccb993bc">  
可以在选择的css文件中加入,不过不确定对性能有没有太大的影响. 

```css
#write{
    background: url(图片存放的路径);
    background-size: 30%;
    background-repeat: no-repeat;
    background-position: right bottom;
}
```
